import type { PeopleData, EncounterVertical } from "./people-types";

// Exact demo seed — values intentionally include verticals outside the
// canonical enum ("General", "Marketplaces") because the demo depends on
// the literal contrast between records. Cast to satisfy TS.
const V = (s: string) => s as EncounterVertical;

const SARAH = "p_sarah";
const MARCUS = "p_marcus";
const DAN = "p_dan";
const LENA = "p_lena";

export const SEED_PEOPLE_DATA: PeopleData = {
  people: [
    {
      id: SARAH,
      fullName: "Sarah Chen",
      nameVariations: [],
      linkedInUrl: "https://linkedin.com/in/sarahchen-demo",
      currentCompany: "PayStream",
      currentRole: "Head of Treasury",
      currentVertical: V("Payments"),
      createdAt: "2025-10-01T00:00:00.000Z",
      createdByRepId: "Yossi",
    },
    {
      id: MARCUS,
      fullName: "Marcus Webb",
      nameVariations: [],
      linkedInUrl: "https://linkedin.com/in/marcuswebb-demo",
      currentCompany: "Independent",
      currentRole: "Independent Consultant",
      currentVertical: V("General"),
      createdAt: "2024-03-01T00:00:00.000Z",
      createdByRepId: "Avi",
    },
    {
      id: DAN,
      fullName: "Daniel Cohen",
      nameVariations: ["Dan Cohen", "Daniel Cohen"],
      linkedInUrl: "https://linkedin.com/in/dancohen-demo",
      currentCompany: "FlowPay",
      currentRole: "VP Payments",
      currentVertical: V("Payments"),
      createdAt: "2025-09-01T00:00:00.000Z",
      createdByRepId: "Yossi",
    },
    {
      id: LENA,
      fullName: "Lena Ortiz",
      nameVariations: [],
      linkedInUrl: "https://linkedin.com/in/lenaortiz-demo",
      currentCompany: "Marqeta-style marketplace",
      currentRole: "Director of Finance",
      currentVertical: V("Marketplaces"),
      createdAt: "2026-03-01T00:00:00.000Z",
      createdByRepId: "Dana",
    },
  ],
  encounters: [
    {
      id: "e1",
      personId: SARAH,
      conferenceId: "EuroFinance 2025",
      conferenceName: "EuroFinance 2025",
      repId: "Yossi",
      timestamp: "2025-10-01T00:00:00.000Z",
      temperature: "warm",
      roleAtTime: "Treasury Analyst",
      companyAtTime: "NovaLogistics",
      note: "Curious about embedded FX, not a buyer yet",
      captureMethod: "manual",
    },
    {
      id: "e2",
      personId: SARAH,
      conferenceId: "Money20/20 2026",
      conferenceName: "Money20/20 2026",
      repId: "Dana",
      timestamp: "2026-03-01T00:00:00.000Z",
      temperature: "hot",
      roleAtTime: "Head of Treasury",
      companyAtTime: "PayStream",
      note: "Now owns FX risk, asked about API pricing",
      captureMethod: "manual",
    },
    {
      id: "e3",
      personId: MARCUS,
      conferenceId: "Money20/20 2024",
      conferenceName: "Money20/20 2024",
      repId: "Avi",
      timestamp: "2024-03-01T00:00:00.000Z",
      temperature: "cold",
      roleAtTime: "Independent Consultant",
      companyAtTime: "Independent",
      note: "Lots of questions, no project",
      captureMethod: "manual",
    },
    {
      id: "e4",
      personId: MARCUS,
      conferenceId: "EuroFinance 2025",
      conferenceName: "EuroFinance 2025",
      repId: "Yossi",
      timestamp: "2025-10-01T00:00:00.000Z",
      temperature: "cold",
      roleAtTime: "Independent Consultant",
      companyAtTime: "Independent",
      note: "Same chat as last year",
      captureMethod: "manual",
    },
    {
      id: "e5",
      personId: MARCUS,
      conferenceId: "Sibos 2025",
      conferenceName: "Sibos 2025",
      repId: "Dana",
      timestamp: "2025-09-01T00:00:00.000Z",
      temperature: "warm",
      roleAtTime: "Independent Consultant",
      companyAtTime: "Independent",
      note: "Friendly, still no buying authority",
      captureMethod: "manual",
    },
    {
      id: "e6",
      personId: DAN,
      conferenceId: "Sibos 2025",
      conferenceName: "Sibos 2025",
      repId: "Yossi",
      timestamp: "2025-09-01T00:00:00.000Z",
      temperature: "warm",
      roleAtTime: "VP Payments",
      companyAtTime: "FlowPay",
      note: "Captured as 'Dan'",
      captureMethod: "manual",
    },
    {
      id: "e7",
      personId: DAN,
      conferenceId: "Money20/20 2026",
      conferenceName: "Money20/20 2026",
      repId: "Dana",
      timestamp: "2026-03-01T00:00:00.000Z",
      temperature: "warm",
      roleAtTime: "VP Payments",
      companyAtTime: "FlowPay",
      note: "Captured as 'Daniel'",
      captureMethod: "manual",
    },
    {
      id: "e8",
      personId: LENA,
      conferenceId: "Money20/20 2026",
      conferenceName: "Money20/20 2026",
      repId: "Dana",
      timestamp: "2026-03-01T00:00:00.000Z",
      temperature: "warm",
      roleAtTime: "Director of Finance",
      companyAtTime: "Marqeta-style marketplace",
      note: "Met at booth",
      captureMethod: "manual",
    },
    {
      id: "e9",
      personId: LENA,
      conferenceId: "Money20/20 2026",
      conferenceName: "Money20/20 2026",
      repId: "Avi",
      timestamp: "2026-03-01T00:00:00.000Z",
      temperature: "hot",
      roleAtTime: "Director of Finance",
      companyAtTime: "Marqeta-style marketplace",
      note: "Met again at side dinner — keen",
      captureMethod: "manual",
    },
  ],
};
