import type { PeopleData } from "./people-types";

// Conference IDs in this seed match the slug-style fallback IDs used when the
// real DB id is unknown. The conferenceName snapshot is what UI displays.
function id(s: string) {
  return s;
}

const SARAH = "seed-person-sarah";
const MARCUS = "seed-person-marcus";
const DAN = "seed-person-dan";
const LENA = "seed-person-lena";

export const SEED_PEOPLE_DATA: PeopleData = {
  people: [
    {
      id: SARAH,
      fullName: "Sarah Chen",
      nameVariations: [],
      linkedInUrl: "https://linkedin.com/in/sarahchen-treasury",
      currentCompany: "PayStream",
      currentRole: "Head of Treasury",
      currentVertical: "Payments",
      createdAt: "2025-09-17T10:00:00.000Z",
      createdByRepId: "Yossi",
    },
    {
      id: MARCUS,
      fullName: "Marcus Webb",
      nameVariations: [],
      linkedInUrl: "https://linkedin.com/in/marcuswebb",
      currentCompany: "Webb Advisory",
      currentRole: "Independent Consultant",
      currentVertical: "Other",
      createdAt: "2024-10-22T10:00:00.000Z",
      createdByRepId: "Dana",
    },
    {
      id: DAN,
      fullName: "Daniel Cohen",
      nameVariations: ["Dan Cohen"],
      linkedInUrl: "https://linkedin.com/in/dancohen-flowpay",
      currentCompany: "FlowPay",
      currentRole: "VP Payments",
      currentVertical: "Payments",
      createdAt: "2025-10-15T10:00:00.000Z",
      createdByRepId: "Avi",
    },
    {
      id: LENA,
      fullName: "Lena Ortiz",
      nameVariations: [],
      linkedInUrl: "https://linkedin.com/in/lenaortiz",
      currentCompany: "Globex",
      currentRole: "Director of Payments",
      currentVertical: "Payments",
      createdAt: "2026-10-19T10:00:00.000Z",
      createdByRepId: "Dana",
    },
  ],
  encounters: [
    // Sarah arc: warm @ EuroFinance 2025 (NovaLogistics, Other) -> hot @ Money20/20 2026 (PayStream, Payments)
    {
      id: id("seed-enc-sarah-1"),
      personId: SARAH,
      conferenceId: "eurofinance-2025",
      conferenceName: "EuroFinance 2025",
      repId: "Yossi",
      timestamp: "2025-09-17T15:30:00.000Z",
      temperature: "warm",
      vertical: "Other",
      note: "Curious, early stage on hedging",
      companyAtTime: "NovaLogistics",
      roleAtTime: "Treasury Analyst",
      captureMethod: "manual",
    },
    {
      id: id("seed-enc-sarah-2"),
      personId: SARAH,
      conferenceId: "money20-20-usa",
      conferenceName: "Money20/20 USA 2026",
      repId: "Dana",
      timestamp: "2026-10-19T11:00:00.000Z",
      temperature: "hot",
      vertical: "Payments",
      note: "Wants embedded FX pricing, intro'd CPO",
      companyAtTime: "PayStream",
      roleAtTime: "Head of Treasury",
      captureMethod: "manual",
    },
    // Marcus arc: 3 encounters, no signal
    {
      id: id("seed-enc-marcus-1"),
      personId: MARCUS,
      conferenceId: "money20-20-usa",
      conferenceName: "Money20/20 USA 2024",
      repId: "Yossi",
      timestamp: "2024-10-22T14:00:00.000Z",
      temperature: "cold",
      vertical: "Other",
      companyAtTime: "Webb Advisory",
      roleAtTime: "Independent Consultant",
      captureMethod: "manual",
    },
    {
      id: id("seed-enc-marcus-2"),
      personId: MARCUS,
      conferenceId: "eurofinance-2025",
      conferenceName: "EuroFinance 2025",
      repId: "Yossi",
      timestamp: "2025-09-18T11:00:00.000Z",
      temperature: "cold",
      vertical: "Other",
      companyAtTime: "Webb Advisory",
      roleAtTime: "Independent Consultant",
      captureMethod: "manual",
    },
    {
      id: id("seed-enc-marcus-3"),
      personId: MARCUS,
      conferenceId: "sibos",
      conferenceName: "Sibos 2025",
      repId: "Avi",
      timestamp: "2025-09-30T09:30:00.000Z",
      temperature: "warm",
      vertical: "Other",
      companyAtTime: "Webb Advisory",
      roleAtTime: "Independent Consultant",
      captureMethod: "manual",
    },
    // Dan/Daniel: name-variation dedup
    {
      id: id("seed-enc-dan-1"),
      personId: DAN,
      conferenceId: "sibos",
      conferenceName: "Sibos 2025",
      repId: "Yossi",
      timestamp: "2025-09-30T13:00:00.000Z",
      temperature: "warm",
      vertical: "Payments",
      note: "Captured as 'Dan Cohen'",
      companyAtTime: "FlowPay",
      roleAtTime: "VP Payments",
      captureMethod: "manual",
    },
    {
      id: id("seed-enc-dan-2"),
      personId: DAN,
      conferenceId: "money20-20-usa",
      conferenceName: "Money20/20 USA 2026",
      repId: "Dana",
      timestamp: "2026-10-19T16:45:00.000Z",
      temperature: "hot",
      vertical: "Payments",
      note: "Captured as 'Daniel Cohen' — same LinkedIn",
      companyAtTime: "FlowPay",
      roleAtTime: "VP Payments",
      captureMethod: "manual",
    },
    // Lena: cross-rep collision at same event
    {
      id: id("seed-enc-lena-1"),
      personId: LENA,
      conferenceId: "money20-20-usa",
      conferenceName: "Money20/20 USA 2026",
      repId: "Dana",
      timestamp: "2026-10-19T10:30:00.000Z",
      temperature: "warm",
      vertical: "Payments",
      companyAtTime: "Globex",
      roleAtTime: "Director of Payments",
      captureMethod: "manual",
    },
    {
      id: id("seed-enc-lena-2"),
      personId: LENA,
      conferenceId: "money20-20-usa",
      conferenceName: "Money20/20 USA 2026",
      repId: "Avi",
      timestamp: "2026-10-19T15:15:00.000Z",
      temperature: "hot",
      vertical: "Payments",
      note: "Avi didn't know Dana already met them",
      companyAtTime: "Globex",
      roleAtTime: "Director of Payments",
      captureMethod: "manual",
    },
  ],
};
