/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ImportRouteImport } from './routes/import'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAgentRunRouteImport } from './routes/api/public/agent/run'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRunRoute = ApiPublicAgentRunRouteImport.update({
  id: '/api/public/agent/run',
  path: '/api/public/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/capture': typeof CaptureRoute
  '/catalog': typeof CatalogRoute
  '/follow-ups': typeof FollowUpsRoute
  '/import': typeof ImportRoute
  '/people': typeof PeopleRoute
  '/planning': typeof PlanningRoute
  '/recap': typeof RecapRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/capture': typeof CaptureRoute
  '/catalog': typeof CatalogRoute
  '/follow-ups': typeof FollowUpsRoute
  '/import': typeof ImportRoute
  '/people': typeof PeopleRoute
  '/planning': typeof PlanningRoute
  '/recap': typeof RecapRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/capture': typeof CaptureRoute
  '/catalog': typeof CatalogRoute
  '/follow-ups': typeof FollowUpsRoute
  '/import': typeof ImportRoute
  '/people': typeof PeopleRoute
  '/planning': typeof PlanningRoute
  '/recap': typeof RecapRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/capture'
    | '/catalog'
    | '/follow-ups'
    | '/import'
    | '/people'
    | '/planning'
    | '/recap'
    | '/settings'
    | '/today'
    | '/api/public/agent/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/capture'
    | '/catalog'
    | '/follow-ups'
    | '/import'
    | '/people'
    | '/planning'
    | '/recap'
    | '/settings'
    | '/today'
    | '/api/public/agent/run'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/capture'
    | '/catalog'
    | '/follow-ups'
    | '/import'
    | '/people'
    | '/planning'
    | '/recap'
    | '/settings'
    | '/today'
    | '/api/public/agent/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  CaptureRoute: typeof CaptureRoute
  CatalogRoute: typeof CatalogRoute
  FollowUpsRoute: typeof FollowUpsRoute
  ImportRoute: typeof ImportRoute
  PeopleRoute: typeof PeopleRoute
  PlanningRoute: typeof PlanningRoute
  RecapRoute: typeof RecapRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  ApiPublicAgentRunRoute: typeof ApiPublicAgentRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/run': {
      id: '/api/public/agent/run'
      path: '/api/public/agent/run'
      fullPath: '/api/public/agent/run'
      preLoaderRoute: typeof ApiPublicAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  CaptureRoute: CaptureRoute,
  CatalogRoute: CatalogRoute,
  FollowUpsRoute: FollowUpsRoute,
  ImportRoute: ImportRoute,
  PeopleRoute: PeopleRoute,
  PlanningRoute: PlanningRoute,
  RecapRoute: RecapRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  ApiPublicAgentRunRoute: ApiPublicAgentRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
